[심기성] QnA 3단계(RESTful API) 구현 완료
sproutt/spring-study-atdd pull request #16
Opened 2019-03-25 03:18 UTC by SimKiSeong

1. api를 restful하게 짜는 고민을 많이 했습니다.
2. createResource, getResource를 이용하여 리팩토링 하였습니다.

2019-03-25 06:46 UTC, wijehyeon reviewed
👍 
QnA도 파이팅

2019-03-25 06:46 UTC, wijehyeon commented on src/main/java/codesquad/domain/Question.java
> +        if (this.title.equals(question.getTitle())) {
제목 내용을 다 비교하면 로직도깊어지는데 
question만 비교하면 안될지?

2019-03-25 06:46 UTC, wijehyeon commented on src/main/java/codesquad/service/QnaService.java
> +            return questionRepository.save(original);
if문 안에만 return이 있는데 throw 되면 반환형 만족하나보군요

2019-03-25 06:46 UTC, wijehyeon commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +    final private static String DEFAULTANSWERURL = "/api/questions/1/answers";
가독성을 위한 SNAKE_CASE

2019-03-25 06:46 UTC, wijehyeon commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +    UserRepository userRepository;
userRepository가 AnswerTest에 필요할까요

2019-03-25 06:46 UTC, wijehyeon commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +        anotherUser = userRepository.findByUserId("sanjigi").orElseThrow(NullEntityException::new);
구현되어있는 코드에서 제공되는 defaultUser나 아니면 추가적인 사용자를 AcceptanceTest에 구현하는것은 어떨지

2019-03-25 06:46 UTC, wijehyeon commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +
로그인 되지 않았을 경우 create되지 않는 경우도 테스트 가능해보입니다

2019-03-25 07:01 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +        return false;
이거 슨 테스트를 위한 코드인것 같습니다.

2019-03-25 07:01 UTC, dadadamarine commented on src/main/java/codesquad/service/QnaService.java
> +        throw new UnAuthorizedException();
if 문밖에서 예외처리를 하신 이유가 있으신가요?

2019-03-25 07:01 UTC, dadadamarine commented on src/main/java/codesquad/service/QnaService.java
> +    public Question delete(User loginUser, long questionId) throws UnAuthorizedException {
정상적인 로직의 경로에 RuntimeException을 던지도록 코딩해두니 delete메서드에서 한예외밖에 처리를 못하는 문제가 발생합니다.
1. delete메서드의 예외는 권한뿐아니라, 이미 삭제된것, 존재하지 않는것 등 다양합니다.
2. 위의 예외를 모두 처리해주기 위해서는 예외를 if문 안의 예외로 처리해야할 것 같습니다.

2019-03-25 07:01 UTC, dadadamarine commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +        basicAuthTemplate(defaultUser()).delete(location);
TestRestTemplate객체에 이런 메서드가 있는지 몰랐습니다.
객체의 메서드들을 파악해서 사용하는 모습이 멋집니다.
좋은것 배워갑니다. 코드가 훨씬 깔끔해질 수 있겠군요.

2019-03-25 07:30 UTC, SimKiSeong commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +        anotherUser = userRepository.findByUserId("sanjigi").orElseThrow(NullEntityException::new);
다른 사용자를 Acceptance에 구현하는게 좋은거 같습니다.

2019-03-25 07:31 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
> +        throw new UnAuthorizedException();
좀더 직관적인거 같아서 이렇게 짰습니다.

2019-03-26 12:45 UTC, SimKiSeong commented on src/main/java/codesquad/domain/Question.java
> +        return false;
그런거 같습니다. 수정하겠습니다.

2019-03-26 12:45 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
> +    public Question delete(User loginUser, long questionId) throws UnAuthorizedException {
중요한 내용인거 같습니다.

2019-03-26 12:45 UTC, SimKiSeong commented on src/test/java/codesquad/web/ApiAnswerAcceptanceTest.java
> +    UserRepository userRepository;
Acceptance Test에 구현하는게 좋을 것 같아요

2019-03-29 12:24 UTC, wijehyeon reviewed
👍

2019-03-29 12:24 UTC, wijehyeon commented on src/main/java/codesquad/domain/Answer.java
> +        this.deleted = true;
사용자 체크를 delete에 구현하지 않고 다른데 하셨나보군요
찾는재미로 리뷰계속해보겠습니다.

2019-03-29 12:24 UTC, wijehyeon commented on src/main/java/codesquad/service/QnaService.java
>      public Question findById(long id) {
findQuestionById라고 네이밍 해주는게 안헷갈릴것 같아요

2019-03-29 12:24 UTC, wijehyeon commented on src/main/java/codesquad/service/QnaService.java
> +        if (!original.isOwner(loginUser)) {
update, delete에 인증부분은 도메인에 구현하게 되면 실수가 일어날 가능성이 떨어진다고 합니다.

2019-03-29 13:38 UTC, esp2ar0 commented on src/main/java/codesquad/service/QnaService.java
> +    public Question update(User loginUser, long id, Question updatedQuestion) throws UnAuthorizedException {
RuntimeException은 체크해주지 않아도 됩니다

2019-03-30 05:49 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
>      public Question findById(long id) {
중요한것 같습니다.

2019-03-30 05:49 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
> +        if (!original.isOwner(loginUser)) {
저는 서비스에서 처리해주는게 도메인에서 간결하고 유저 확인하는 코드를 그만큼 적게 써서 오히려 실수가 덜 날 것 같은데
코드를 도메인 부분에 짜면 실수가 덜 일어난다는게 어떤 의미에서 그런 건지 설명 부탁드립니다.

2019-03-30 05:49 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
> +    public Question update(User loginUser, long id, Question updatedQuestion) throws UnAuthorizedException {
RuntimeException은 체크해주지 않아도 된다는게 어떤 말인지 잘 이해가 되지 않습니다.

2019-03-30 07:09 UTC, wijehyeon commented on src/main/java/codesquad/service/QnaService.java
> +        if (!original.isOwner(loginUser)) {
지난 해커톤때 느껴본 것 처럼 만약에 기성님이 domain을 만들었고
다른사람이 그 domain을 가져다 쓰는 일이 생겼다고 가정해보면 
update, delete같은 메소드는 권한체크가 아주 중요한 함수들인데 service에 구현되는 것 보다
domain에 구현되어 있으면 도메인에 미리 방어를 해두는 격입니다.
물론 service에 권한을 체크해줘도 되지만, 더 하위에 있는 객체에 있으면 어쨋든 객체에 접근하는 로직이니까 
무책임한 서비스로직에 대한 방어가 더 잘 될 것이라고 생각합니당

2019-03-30 17:59 UTC, SimKiSeong commented
1. 유저체크를 도메인부분으로 이동했습니다.
2. 일부 메소드명을 수정하였습니다.

2019-03-31 03:51 UTC, hyukjin-lee requested changes
?? 시간을 거슬러올라가는 리팩토링을 본 것 같습니다.

2019-03-31 03:51 UTC, hyukjin-lee commented on src/main/java/codesquad/service/QnaService.java
> +        return questionRepository.save(question);
delete하고 save 하면 어떻게 되나요? DB에서 값들이 null로 대치되는건지 아니면 해당 레코드가 삭제되는건지 궁금합니다

2019-03-31 03:51 UTC, hyukjin-lee commented on src/main/java/codesquad/web/ApiAnswerController.java
> +        return qnaService.updateAnswer(answer, updatedContents);
로직은 service에 있어야하지 않을까요?

2019-03-31 03:51 UTC, hyukjin-lee commented on src/main/java/codesquad/web/QuestionController.java
> +        qnaService.deleteQuestion(question);
로직을 서비스에서 다시 끄집어낸 것 같은데 왜 그런거죠?

2019-03-31 04:59 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
> +        return questionRepository.save(question);
delete 할때 모든 값을 없에는게 아니라 boolean타입의 delete객체의 값만 false로 바꿔줍니다.
그래서 delete로 값만 바꾼후에 다시 저장해주게 짰습니다.

2019-03-31 05:01 UTC, SimKiSeong commented on src/main/java/codesquad/web/ApiAnswerController.java
> +        return qnaService.updateAnswer(answer, updatedContents);
이해를 잘못해서 잘못 만들었습니다.
다시 코쳐서 커밋하겠습니다.

2019-03-31 05:40 UTC, merged

2019-03-31 09:46 UTC, esp2ar0 commented on src/main/java/codesquad/service/QnaService.java
> +    public Question update(User loginUser, long id, Question updatedQuestion) throws UnAuthorizedException {
Exception을 상속하는 체크 예외(Checked Exception)
RuntimeException을 상속하는 언체크 예외(Unchecked Exception)에 대한 말이였어요
throws 처리나, try catch