[위제현] QnA 4단계(객체지향개발) 구현 완료
sproutt/spring-study-atdd pull request #18
Opened 2019-03-28 13:56 UTC by wijehyeon

* [x] : 질문 삭제기능 구현
* [x] : 질문과 답변 삭제 이력에 대한 정보를 DeleteHistory를 활용해 남긴다.
* [x] : FunctionWithException을 활용하여 lamda에서 checked exception 구현(https://www.slipp.net/questions/572)

2019-03-29 11:27 UTC, dadadamarine reviewed
전체적으로 깔끔하네요.

2019-03-29 11:27 UTC, dadadamarine commented on src/main/java/codesquad/domain/Answer.java
>              throw new CannotDeleteException("User not equal");
delete요청에 관계된 예외는, 권한에러도 UnAuthrized대신 CannotDeleteException을 사용하셨네요. 어떤점을 의도하셨는지 듣고싶습니다.

한가지 제가 걱정되는 부분은  delete메서드 하나에 대한 예외가 CannotDeleteException 객체에 파라미터만 바꿔서 프론트에 전달된다고 하면. Response의 상태코드를 CannotDeleteException 에 매칭된 한종류로 밖에 전달 못할겁니다.

프론트에서는 로그인이 안되서 실패되면 로그인 페이지로 구분해서 보내줘야 하는데  왜 에러가 난건지 구분이 안되는 상황이 발생할 것 같습니다.

2019-03-29 11:27 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +    @OrderBy("id ASC")
와 이거 쓰셨군요. 삭제된 애들도 answers에 들어가는거 처리하는거때문에 고민했었는데 좋은것 배워갑니다.

2019-03-29 11:27 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +        return histories;
for each대신 map을쓰신 이유가 있으신가요?

2019-03-29 11:27 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +        return histories;
첨부해주신 글을 읽어보았으나, 왜 이부분을 wrapper로 따로 처리를 해야하는지 아직 이해못했습니다.
저는 람다식의 각 메서드가 다른 쓰레드에서 돈다고 하더라도, 예외가 왔을때의 목적지는 결국 이 메서드이고, 
그래서 람다식 안에서 unAuth예외가 난다면 이 delete메서드 밖으로 unAuth예외를 던져주고, 
Transactional 어노테이션때문에 이전에 것들이 롤백되고, unAuth를 ControllerAdvice가 처리해 BAD_REQUEST로 상태코드로 만들어 줄것이라고 기대하였습니다.
또한 관련 테스트또한 expected = unAuth~ 예외 검출로 테스트 성공하였습니다.

2019-03-29 11:27 UTC, dadadamarine commented on src/test/java/codesquad/domain/QuestionTest.java
> +    }
단위테스트를 깔끔하게 구현하셨군요. 본받겠습니다.

2019-03-29 13:24 UTC, esp2ar0 requested changes

2019-03-29 13:24 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +    @OrderBy("id ASC")
이거 기본 코드로 주어지던데요??

2019-03-29 13:24 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Answer.java
> +    public DeleteHistory delete(User loginUser) throws Exception {
저번 리뷰에서 언급한 적이 있었던 것 같은데, 예외를 잡거나 던질 때는 최대한 좁은 범위로 해야합니다.
이유는 아시겠죠?

2019-03-29 13:24 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Answer.java
>              throw new CannotDeleteException("User not equal");
개인적으로 이 부분은 UnAuthorized가 더 적절해보이는군요

저같은 경우는 CannotDeleteException을 사용하지 않았습니다. 이름이 모호해서 어디다가 써야할 지 모르겠더라구요

2019-03-29 13:24 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +        this.deleted = true;
답변 부분을 삭제하는게 먼저 와야하지 않을까요?
답변을 삭제하다가 에러가 발생할 수도 있으니까요

2019-03-29 13:24 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +    }
if는 {}로 감싸주었으나 else는 그렇지 않았네요. 맞춰주는게 좋겠죠?
또한 else를 굳이 안써주고 return false하는게 더 좋아보입니다.
인자로 받아온 User는 쓰이지 않았군요

2019-03-29 13:24 UTC, esp2ar0 commented on src/main/java/codesquad/service/QnaService.java
> -        answerRepository.save(answer);
save를 지우신 이유가 있나요?
save를 해주지 않아도 update가 되긴 하지만 그것은 관리받고 있기 때문이며
저는 그래도 안전하게 적어주는게 맞다고 생각합니다

2019-03-30 00:17 UTC, wijehyeon commented on src/main/java/codesquad/domain/Question.java
> +        this.deleted = true;
정말 좋은 포인트입니다

2019-03-30 00:21 UTC, wijehyeon commented on src/main/java/codesquad/service/QnaService.java
> -        answerRepository.save(answer);
delete history만 생각하다가 그만 지워버렸네요 감사합니다 👍

2019-06-03 07:52 UTC, merged