[심기성] QnA 4단계(객체지향개발) 구현 완료
sproutt/spring-study-atdd pull request #22
Opened 2019-03-31 09:19 UTC by SimKiSeong

1. 질문 삭제와 관련된 코드를 먼저 구현하였습니다.
2. service가 아닌 question에 delete기능을 구현하였습니다.
3. deletehistory에 삭제기록을 담았습니다.

2019-04-01 13:01 UTC, dadadamarine reviewed
파이팅입니다!

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/domain/DeleteHistory.java
> +        this.createDate = LocalDateTime.now();
객체의 필드부분에 아래와 같은 소스가 있습니다.
```
private LocalDateTime createDate = LocalDateTime.now();
```
위의 이부분에서 이미 createDate의 초기값이 정의되어 있습니다.

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +    }
코드도 하나의 글이라고 생각합니다.
흐름에 맞게 쓰여있으면 읽기 편하지만, 코드가 위아래가 바껴있거나 하면 읽기가 힘들어 지는것 같네요.
현재 소스에서 question을 삭제하는 소스가 하부의 answer을 검사한다음에 오니 뭔가 논리에 안맞는 느낌을 받았습니다.
question을 먼저 삭제하고 answer을 삭제하더라도, answer에서 오류가 난다면 @Transactional 어노테이션의 기능으로 전체 롤백이 일어난다는 점을 이용하시면 좋을 것 같습니다.

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +    }
```
@OneToMany(mappedBy = "question", cascade = CascadeType.ALL)
    @Where(clause = "deleted = false")
    @OrderBy("id ASC")
    private List<Answer> answers = new ArrayList<>();
```
기능을 구현하기 전에 기존 소스에 대한 리딩과 이해를 더 하면 좋을것 같습니다.
unDeletedAnswer는 불필요한 메서드 입니다.

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +        answers = answers.stream().map(answer -> answer.delete()).collect(Collectors.toList());
answers를 다시 이렇게 다시 선언할 필요가 있는지 한번 생각해보시는게 좋을것 같습니다.
현재 이소스는 answer들을 삭제하는 메서드라기보다 answer를 삭제해서 재 할당하는 메서드라고 보는게 맞는것 같습니다.
answer.delete의 행동의 주체는 answer이여야 합니다.

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/domain/Question.java
> +        return true;
예외를 활용하시면 question 삭제에 관한 메서드들이 훨씬 간결해 질것 같습니다.
리팩토링이 필요해 보입니다.

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/service/DeleteHistoryService.java
> +    }
메서드가 이름에서 잘못된 정보를 주고있습니다.
이 메서드의 역할은 history를 저장하는것이지 삭제된 Answer를 저장하는 역할이 아닙니다.

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/service/QnaService.java
> +        return answerRepository.findById(id).orElseThrow(() -> new EntityNotFoundException());
EntityNotFoundException에 대한 예외처리가 filechanged에 뜨지않아서 여쭤봅니다. controllerAdvice에서 처리된 예외인가요?
처리됬다면 상태코드는 어떻게 지정해주셨나요?

2019-04-01 13:01 UTC, dadadamarine commented on src/main/java/codesquad/service/DeleteHistoryService.java
> +    }
질문뿐 아니라 답변도 삭제될시 deleteHistory로 기록되어야 합니다.

2019-04-02 06:31 UTC, esp2ar0 requested changes
그동안 밀려있던 미션을 해결하느라 고생이 많았습니다. 아쉬운 점 코멘트 남겨보아요.
- 프로덕션 코드만 간단히 살펴봤는데, 급하게 코딩한 것 같은 느낌을 강하게 받았습니다. 본인이 세운 목표 달성을 위해 풀리퀘를 빨리 날리는 것은 중요한 게 아닙니다. 한 단계의 미션을 하나씩 해결해나가면서 **미션 도중 알게 된 지식**들이 중요해요. 그것을 쌓아가며 더 나은 방향으로 발전했으면 합니다.
- 기본 코드로서 주어진 것을 잘 활용했으면 좋겠습니다. 더 나은 방식이 있다면 바꾸는 것이 좋지만, 본인이 그것을 많이 바꾸면서 코딩하면서 코드가 더 복잡해진 느낌이에요. 
- 스트림을 많이 사용하는 것은 좋으나, 그것으로 인해 가독성이 떨어지는 경우가 있습니다. 경우에 맞게 사용하는게 좋겠습니다.

2019-04-02 06:31 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +        return true;
이 메소드의 네이밍만 봤을 때 무슨 일을 하는지 잘 모르겠고
여기서 사용되는 differentWriterNumber 또한 어색합니다.
객체지향적으로 코딩돼있지 않다는 느낌입니다

2019-04-02 06:31 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +            deleteAllAnswer();
Answer를 삭제하는게 왜 Question에 있죠?

2019-04-02 06:31 UTC, esp2ar0 commented on src/main/java/codesquad/service/QnaService.java
> +    public Question findQuestionById(long id) throws Exception {
EntityNotFoundException은 RuntimeException인데 throws Exception을 해줬습니다.
저번 리뷰에도 해당 언급이 있었는데 또 이렇게 했다는 것은, 관련 부분을 제대로 확인하고 넘어가지 않았다고 보여지는군요

2019-04-02 08:31 UTC, wijehyeon reviewed
좋은 리뷰들이 많네요

2019-04-02 08:31 UTC, wijehyeon commented on src/main/java/codesquad/domain/Question.java
> +        return (int) unDeletedAnswer().filter(answer -> !answer.isOwner(loginUser)).count();
형 변환 안해주면 에러났던가요?

2019-04-02 08:31 UTC, wijehyeon commented on src/test/java/codesquad/web/ApiQuestionAcceptanceTest.java
> +                basicAuthTemplate(anotherUser).exchange(nullQuestionUrl, HttpMethod.DELETE,null,void.class);
라인정렬 안된 것 같습니다 ㅎ

2019-04-03 02:32 UTC, SimKiSeong reviewed
DeleteHistory랑 JPA에 대한 이해가 부족했던거 같습니다. 잘 이해하고 리팩토링때 반영해보겠습니다.

2019-04-03 02:32 UTC, SimKiSeong commented on src/main/java/codesquad/domain/Question.java
> +        return (int) unDeletedAnswer().filter(answer -> !answer.isOwner(loginUser)).count();
count가 long을 반환해 줘서 int로 형변환 했습니다.

2019-04-03 02:32 UTC, SimKiSeong commented on src/main/java/codesquad/domain/Question.java
> +    }
이 부분 때문에 코드가 이상해졌던거 같습니다 재대로 이해하고 리펙토링 하겠습니다.

2019-04-03 02:32 UTC, SimKiSeong commented on src/main/java/codesquad/domain/Question.java
> +    }
코드 순서가 중요한거 같습니다. 순서에 맞게 리팩토링 하겠습니다.

2019-04-03 02:32 UTC, SimKiSeong commented on src/main/java/codesquad/domain/DeleteHistory.java
> +        this.createDate = LocalDateTime.now();
확인 했습니다. 꼼꼼히 잘 살피겠습니다.

2019-04-03 02:32 UTC, SimKiSeong commented on src/main/java/codesquad/service/QnaService.java
> +    public Question findQuestionById(long id) throws Exception {
풀 리퀘 이후에 설명이 달려서 리팩토링때 반영 하겠습니다.

2019-04-03 02:32 UTC, SimKiSeong commented on src/test/java/codesquad/web/ApiQuestionAcceptanceTest.java
> +                basicAuthTemplate(anotherUser).exchange(nullQuestionUrl, HttpMethod.DELETE,null,void.class);
확인했습니다.

2019-06-03 07:51 UTC, merged