[종근] QnA 4단계(객체지향개발) 구현 완료
sproutt/spring-study-atdd pull request #23
Opened 2019-04-03 10:32 UTC by Bellroute

- AcceptanceTest에 delete 테스트 추가
- QnaServiceTest에 delete 테스트 추가
- ApiQuestionController에 delete 맵핑 추가
- Question, Answer 단위 테스트
- QnaService에 삭제 기능 구현
- DeleteHistoryService 적용

실수로 깜빡해서 도메인 단위 테스트를 뒤늦게 구현했습니다...

2019-04-04 08:16 UTC, esp2ar0 requested changes
이번엔 데드라인을 잘 지켰군요. 고생하셨습니다

2019-04-04 08:16 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Answer.java
> +    private List<DeleteHistory> histories = new ArrayList<>();
이걸 왜 전역변수로 써줬나요?

2019-04-04 08:16 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Answer.java
> +        return histories;
결국 DeleteHistory객체 하나만 리턴하게 되는데,
어째서 List로 반환값을 하고 그 하나를 리스트에 추가해서 리턴해줬나요?

2019-04-04 08:16 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +        return histories;
이 부분도 Answer와 마찬가지입니다.

2019-04-04 08:16 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +        return histories;
또한, 
> 질문을 삭제할 때 답변 또한 삭제해야 하며, 답변의 삭제 또한 삭제 상태(deleted)를 변경한다.

답변을 같이 삭제하는 코드는 보이지 않네요

2019-04-04 08:16 UTC, esp2ar0 commented on src/main/java/codesquad/service/QnaService.java
> +        deleteHistoryService.saveAll(histories);
지금같은 코드에서는 어짜피 histories의 원소는 하나네요.

2019-04-04 08:48 UTC, wijehyeon commented on src/main/java/codesquad/domain/Answer.java
> +            throw new CannotDeleteException("wrong user");
UnAuthorizedException에서 바꾸신 이유가 뭔지 궁금합니다.

2019-04-04 08:48 UTC, wijehyeon commented on src/main/java/codesquad/domain/Question.java
>          this.deleted = true;
answers가 empty일때도 삭제하고
if문을 벗어나서도 삭제하고
낭비되는 부분같습니다

2019-04-09 05:58 UTC, Bellroute commented
1차 리뷰 반영했습니다.

1.DeleteHistory에 대한 레이어별 처리
2.질문 삭제 시, 답변 삭제
3.낭비되는 if문 제거

2019-06-03 07:51 UTC, merged