[병재] QnA 2단계(로그인 상태) 구현완료하였습니다. 리뷰부탁드립니다.
sproutt/spring-study-atdd pull request #27
Opened 2019-10-08 16:28 UTC by jbj616

remote 브랜치 삭제하고 기존 브랜치 이름 바꿔서 다시 pr날립니다~!

2019-10-09 09:04 UTC, esp2ar0 requested changes
열심히 리뷰 했습니다..^^ 도움이 되길 바랍니다

2019-10-09 09:04 UTC, esp2ar0 commented on src/test/java/codesquad/web/QuestionAcceptanceTest.java
> +        ResponseEntity<String> response = basicAuthTemplate(loginUser).getForEntity(String.format("/questions/%d/form", defaultQuestion().getId()), String.class);
basicAuthTemplate() 메소드를 사용하면 여기서 유저를 할당해주지 않아도 될 것 같은데요, 이렇게 짜신 이유가 있나요?

2019-10-09 09:04 UTC, esp2ar0 commented on src/test/java/codesquad/web/QuestionAcceptanceTest.java
> +        ResponseEntity<String> response = basicAuthTemplate(loginUser).getForEntity(String.format("/questions/%d/form", defaultQuestion().getId()), String.class);
아래 createForm_no_login 테스트도 해당되는 사항인데 
/questions/{id}/form은 updateForm의 URL이지 않나요?
createForm의 URL을 일부러 updateForm으로 지정해주신건가요? 만약 그렇다면 왜 그렇게 하셨나요?

2019-10-09 09:04 UTC, esp2ar0 commented on src/test/java/codesquad/web/QuestionAcceptanceTest.java
> +        return template.postForEntity(String.format("/questions/%d", defaultUser().getId()), request, String.class);
put 메소드를 이렇게 테스트 할 수도 있군요. 저는 postForEntity라는 메소드는 postmapping용이라고 생각해서 postForEntity와 put Parameter의 조합이 아닌 별도의 메소드를 사용했었습니다. 병재님은 이렇게 사용하신 이유가 있을까요?

2019-10-09 09:04 UTC, esp2ar0 commented on src/main/java/codesquad/service/QnaService.java
> +        return question;
지금 코드 상에는 에러가 없지만 save 메소드의 인자로 넘겨줬던 객체를 사용하는 것은 에러를 초래할 수 있습니다. 인자로 넘겨준 객체보단 반환된 객체를 사용하는 것이 좋은 습관입니다. 관련 내용을 찾아보세요.
키워드 : JPA Persistence

2019-10-09 09:04 UTC, esp2ar0 commented on src/main/java/codesquad/web/QuestionController.java
> +    private QnaService qnaService;
어디는 private final이고 어디는 private이네요

2019-10-09 09:04 UTC, esp2ar0 commented on src/main/java/codesquad/domain/Question.java
> +    private void isOwner(User loginUser) throws UnAuthorizedException {
boolean의 네이밍 컨벤션인데 void 타입이군요. 이 메소드에 문제가 없는지 고민해보세요

2019-10-12 14:20 UTC, jbj616 commented on src/test/java/codesquad/web/QuestionAcceptanceTest.java
> +        ResponseEntity<String> response = basicAuthTemplate(loginUser).getForEntity(String.format("/questions/%d/form", defaultQuestion().getId()), String.class);
1. 처음에는  유저를 할당해주어야하는 줄 알았습니다. 그리고 test과정에서 user정보가 필요할 때가 있고 기존에 이미 deaultUser가 구현되어있어서 사용하였습니다. 필요하지 않는 곳엔 사용하지 않도록 수정하겠습니다.
2. 앗 실수입니다. 감사합니당

2019-10-12 14:20 UTC, jbj616 commented on src/test/java/codesquad/web/QuestionAcceptanceTest.java
> +        return template.postForEntity(String.format("/questions/%d", defaultUser().getId()), request, String.class);
addParameter에 들어가는 부분이 실제로 front쪽에서 입력되는 부분이기에 입력을 동일하게 할 필요성을 느껴서 `.addParameter("_method", "put")` 이부분을 추가하였고 실제로 이 코드를 작성하므로써 putmapping을 test할 수 있었습니다.

2019-10-12 14:20 UTC, jbj616 commented on src/main/java/codesquad/web/QuestionController.java
> +    private QnaService qnaService;
기존 @resource를 생성자 주입으로 변경후 -> private final 적용 하는 과정에서 착오가 있었네요

2019-10-12 14:20 UTC, jbj616 commented on src/main/java/codesquad/domain/Question.java
> +    private void isOwner(User loginUser) throws UnAuthorizedException {
기존에 boolean 메소드였는 데 에러 발생부분을 Question객체쪽로 옮기는 과정중에 착오가 있었습니다 그리고 객체를 반환하는 형식으로 변경하였습니다. 이유는 위위 리뷰에서 영감을 얻었습니다. 감사합니다

2019-10-12 14:28 UTC, jbj616 commented
리뷰감사합니다!

2019-10-13 11:16 UTC, esp2ar0 commented on src/main/java/codesquad/service/UserService.java
> +        return user.checkSameUser(loginUser);
제 리뷰는 JPA 영속성 관리 측면에서 코드가 확장될 경우 버그가 생길 수 있다는 것이었는데요.
이 부분은 기존의 코드에서 수정하신 이유가 궁금합니다.

또한, 제가 기존에 코멘트 달았던 부분에 대해 어떻게 이해하셨는지도 궁금하네요

2019-10-13 12:03 UTC, jbj616 commented on src/main/java/codesquad/service/UserService.java
> +        return user.checkSameUser(loginUser);
처음에 repository.save 하고 리턴된 값을 사용하면(저장된 데이터를 사용) save가 실행됬다는 점이 확실해진다는 생각으로 User객체에도 적용해 보았습니다.. 약간 억지이긴합니다..
제가 이해한 바로는 데이터베이스에 저장이 이루어지지 않았을 경우 문제가 발생 할 것이라고 생각햇습니다. 평소에는 save하고 변경해도 문제가 없지만 만약 Transactional 에노테이션이 있을 때 문제가 발생한 것을 확인 할 수 있었습니다.
```
//데이터 변경
repository.save()
--> db 에 잘 저장됨.
    
    
repository.save()
//데이터변경
--> db에 잘 저장됨.
    
@Transactional 어노테이션 있을때
repository.save()
//데이터 변경
    
--> db에 저장되지 않음. -> 해결책 savAndFlush 사용
```
가장 중요학 핵심은 데이터가 저장(영속)됐는지가 중요한 것 같습니다.

2019-10-13 12:12 UTC, esp2ar0 commented on src/main/java/codesquad/service/UserService.java
> +        return user.checkSameUser(loginUser);
억지 아니에요 ㅎㅎ 코드가 깔끔해져서 좋다고 생각되네요

```
repository.save()
//데이터변경
--> db에 잘 저장됨.
```
이 경우는 save 다음에 데이터를 변경해줬는데 어째서 db에 반영이 된 걸까요?

2019-10-13 12:45 UTC, jbj616 commented on src/main/java/codesquad/service/UserService.java
> +        return user.checkSameUser(loginUser);
메소드에서 save할때 insert 요청이 일어나고 변경사항이 있을시 메소드가 끝날때 update 요청을 하는 것으로 압니다

2019-10-13 13:15 UTC, esp2ar0 commented on src/main/java/codesquad/service/UserService.java
> +        return user.checkSameUser(loginUser);
update 요청을 하는 기준이 뭔가요? 메소드가 끝날 때 존재하는 모든 객체인가요?

2019-10-13 14:24 UTC, jbj616 commented on src/main/java/codesquad/service/UserService.java
> +        return user.checkSameUser(loginUser);
데이터들이 수정되고 1차 캐시와 비교 하여 데이터 변경여부를 판단합니다 그 후 변경이 감지되면 db에 반영합니다. 데이터가 저장될 동일한 id값에만 해당합니다

2019-10-13 15:01 UTC, esp2ar0 approved these changes
merge하세요~

2019-10-15 04:36 UTC, merged