[정민석] ATDD기반 로그인 기능 구현
sproutt/spring-study-atdd pull request #3
Opened 2019-03-09 05:36 UTC by dadadamarine

1. login 메서드 작성 및 테스트를 모두 통과하였습니다.
2. HtmlFormDataBuilder클래스 생성 및 테스트 코드 리팩토링을 하였습니다.
3. Exception에 관한 공부를 하였습니다.

2019-03-09 10:02 UTC, hyukjin-lee approved these changes

2019-03-09 10:02 UTC, hyukjin-lee commented on src/main/java/codesquad/service/UserService.java
> +	}
해커톤 때 바꾼 space tab 컨벤션 때문에 생긴 불필요한 diff 네요. 확인 부탁드립니다.

2019-03-09 10:02 UTC, hyukjin-lee commented on src/main/java/codesquad/service/UserService.java
> +		return authorizedUser;
findByUserId가 옵셔널을 반환하기 때문에 filter를 적용해도 비번 거를 수 있을 것 같습니다. (Optional은 1개의 스트림과 같다고 생각하면 됌. 그래서 Stream 관련 메소드들 사용가능)

2019-03-09 10:02 UTC, hyukjin-lee commented on src/main/java/support/utils/HtmlFormDataBuilder.java
> +	}
test에서 사용되는 클래스인데 production 코드에 있는건 잘못된 것 같습니다.

2019-03-09 10:02 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +		HtmlFormDataBuilder builder = HtmlFormDataBuilder.urlEncodedForm();
디자인 패턴 중에 Builder 패턴을 공부하고 이 클래스를 다시 활용해서 리팩토링 해보시는게 좋을 것 같습니다. 가장 흔히 쓰이고 중요한 패턴이라

2019-03-09 10:02 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +	public void login_fail() throws Exception {
아... 저는 로그인 통과만 구현했는데,, 여러 경우를 고려해서 짜야한다는 기본을 놓치고 있었네요. 한 수 배우고 갑니다.

2019-03-09 10:02 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FOUND);
아 post 성공하면 기본적으로 FOUND가 날라오나보군요

2019-03-09 10:02 UTC, hyukjin-lee commented on src/test/java/codesquad/web/UserAcceptanceTest.java
> +		builder.addParameter("email", "javajigi@slipp.net");
이 클래스에 구현된 함수들의 반환값들을 한번 잘 봐보시고 리팩토링해보세요.

2019-03-09 15:25 UTC, dadadamarine commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +		assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FOUND);
found와 같은 300번대 코드는 redirect 때문에 날라오는것으로 알고있습니다.

2019-03-09 15:26 UTC, dadadamarine commented on src/test/java/codesquad/web/UserAcceptanceTest.java
> +		builder.addParameter("email", "javajigi@slipp.net");
아 builder의 예시에 왜 class가 있을까 void로 고칠까 의아했었는데 지금보니 사용법을 알겠군요. 이해했습니다 감사합니다

2019-03-10 02:45 UTC, hyukjin-lee commented on src/main/java/codesquad/service/UserService.java
> +	}
이래서 개발자들이 space냐 tab이냐 컨벤션 맞추는 것 같습니다. 버전관리 시 불필요한 diff가 생기니깐요

2019-03-10 02:46 UTC, hyukjin-lee commented on src/test/java/codesquad/web/UserAcceptanceTest.java
> +		builder.addParameter("email", "javajigi@slipp.net");
이런 방식을 메소드 체이닝 방식이라고 합니다

2019-03-10 07:33 UTC, wijehyeon reviewed
👍

2019-03-10 07:33 UTC, wijehyeon commented on src/main/java/codesquad/web/UserController.java
> +	@Resource(name = "userService")
name을 지정해주면 뭐가좋나요?

2019-03-10 07:55 UTC, dadadamarine commented on src/main/java/codesquad/web/UserController.java
> +	@Resource(name = "userService")
덕분에 또 좋은거 배웠습니다. 
위의 경우엔 해당되지 않습니다만. Resource(name ="")이용하는경우는 아래와 같다고 합니다.
1. userService 를 상속받는 서비스들이 존재하여 UserService가 될수있는 객체가 여러개인 경우
    - applicaion context에서 어떤 UserService를 주입해야하는지 알수 없음.
```
@Service
public KoreaService extends UserService{
   //....
}
```

```
@Autowired
public UserService userService 
```

위의 경우 
```
@Resource(name="userDao")
BaseDao baseDao
```
와 같이 사용해 주면 된다고 합니다.

참고자료 : https://stackoverflow.com/questions/10780872/spring-injection-of-resource-fields-failed

2019-03-10 08:46 UTC, esp2ar0 requested changes

2019-03-10 08:46 UTC, esp2ar0 commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +public class LoginAccpetanceTest {
위의 에노테이션과 아래 코드의 몇 부분은 기본 뼈대 클래스인 AcceptanceTest에 구현 돼 있습니다.
UserAcceptanceTest를 참고해보세요. 에노테이션을 안 써준 것을 확인할 수 있습니다
또한 클래스명 오타났네요

2019-03-10 13:30 UTC, dadadamarine commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +public class LoginAccpetanceTest {
이부분을 고민을 좀 했었는데요.
현재 AcceptanceTest는 클라이언트의 로그인을 건너뛰고 테스트하기 위한 파일입니다.
![image](https://user-images.githubusercontent.com/28672263/54085685-f8798100-4383-11e9-873e-c2a827ab6642.png)
설명을 보면 위의 1번째 요청을 건너뛰고 2번째 요청으로 클라이언트에서 바로 서버로 request를 보내는 방식입니다.

하지만 로그인 테스트를 하기위해선 1번째 요청방식을 이용하는게 더 맞을것 같아 일부러 AcceptaceTest를 상속받지 않고 따로 구현을 하였습니다.

2019-03-11 00:59 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAccpetanceTest.java
> +public class LoginAccpetanceTest {
AcceptanceTest는 로그인을 건너뛰기 위한 클래스가 아니라 인수테스트를 위해 작성된 추상클래스입니다. 로그인을 테스트하기 위해서 1번째 방식을 이용했다고 했는데, 제 눈에 보이는건 2번째 방식 뿐입니다. 1번째 방식까지 모두 포함한 테스트를 작성하려면 /user/login에 get 요청을 하고 결과로 받아온 값을 검증하고 다시 /user/login으로 post 요청을 보내는 것 까지 모두 하나의 테스트에 작성되어야합니다. 인수테스트는 올바른 페이지를 내려주는걸 테스트하는 용도가 아니라 기능이 잘 동작하는지 크게 테스트 하는겁니다. /user/login 으로 get요청을 보내서 login form이 반환되는걸 확인하는 테스트는 컨트롤러 단위테스트로 작성되어 서버를 띄우지 않고도 가볍게 돌아갈 수 있게 해야합니다.

2019-03-11 01:10 UTC, SimKiSeong commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +        assertThat(userRepository.findByUserId(userId).isPresent()).isFalse();
이 부분은 레파지토리에 유저가 있는지 없는지 확인하는 메소드 인데
login_fail과 관련성이 적어 보입니다.

2019-03-11 01:10 UTC, SimKiSeong commented on src/main/java/codesquad/web/UserController.java
> +	public String login(HttpSession httpSession, String userId, String password) {
Optional을 활용해 로그인 기능을 구현해보라는 문구가 있었습니다.
Optional을 활용해 로그인 기능을 구현해 보는 것도 좋을 것 같습니다.

2019-03-12 04:25 UTC, merged