[위제현] ATDD기반 로그인 기능 구현
sproutt/spring-study-atdd pull request #4
Opened 2019-03-10 07:22 UTC by wijehyeon

* [x] UserController 로그인 기능 구현
* [x] LoginAcceptance 테스트 통과 완료
* [x] 로그인 DTO를 통해서 userId, password 접근, 전달
* [x] UserServiceTest의 모든 테스트 메소드가 성공

2019-03-10 07:58 UTC, dadadamarine commented on src/main/java/codesquad/web/UserController.java
> +	}
제현님도 해커톤때 설정한 기본 코드스타일(space tab 컨벤션)때문에 불필요한

2019-03-10 08:04 UTC, dadadamarine requested changes
UserAcceptanceTest도 HtmlFormDataBuilder.java사용하여 리팩토링 가능해 보입니다.

- 전체적으로 깔끔하고 잘 구현하신것 같습니다.

2019-03-10 08:04 UTC, dadadamarine commented on src/main/java/codesquad/web/dto/LoginDTO.java
> +	}
BasicAuthInterceptor.java 파일에서  
`User user = userService.login(new LoginDTO(values[0], values[1]));`
라고 사용하셨는데 DTO에는 해당되는 생성자가 없네요, 정상작동 하나요?

2019-03-10 08:18 UTC, esp2ar0 commented on src/main/java/codesquad/web/UserController.java
> +	}
난 이런문제 없는거같은디

2019-03-10 08:51 UTC, esp2ar0 requested changes

2019-03-10 08:51 UTC, esp2ar0 commented on src/main/java/codesquad/web/dto/LoginDTO.java
> +public class LoginDTO {
User에 대한 DTO인 만큼 네이밍시 User가 포함되는게 좋지 않을까요?

2019-03-10 08:51 UTC, esp2ar0 commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +	private static final Logger log = LoggerFactory.getLogger(UserAcceptanceTest.class);
클래스 인자를 보아하니 UserAcceptanceTest 클래스에서 복사된 코드로 보이는데,
이 클래스에서 사용되고 있지 않네요

2019-03-10 08:57 UTC, wijehyeon commented on src/main/java/codesquad/web/dto/LoginDTO.java
> +public class LoginDTO {
String userId, String password 두가지 정보가 다라면
User이기 전에 Login에 해당하는 정보라고 생각했었는데
UserLoginDTO 이런식으로 포함하는것도 좋겠군요

2019-03-10 08:57 UTC, wijehyeon commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +	private static final Logger log = LoggerFactory.getLogger(UserAcceptanceTest.class);
아 참고만 한다는게 그만.. 수정하겠습니다

2019-03-11 07:48 UTC, SimKiSeong commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +		assertThat(userRepository.findByUserId("sanjigi").isPresent());
Login 을 확인하는 메소드 인데 이 부분은 어울리지 않는것 같습니다.

2019-03-12 04:41 UTC, merged