[종근] QnA 1단계(ATDD 시작) 구현 완료
sproutt/spring-study-atdd pull request #7
Opened 2019-03-10 14:49 UTC by Bellroute

- LoginAcceptanceTest를 구현
- UserController에 "/users/login"요청에 대응하는 서버측 코드를 구현
- UserService에 login()메소드 구현 -> UserServiceTest 통과
- UserController의 login로직 UserService로 위임
- POST에 대한 테스트 코드의 중복 제거를 위한 리팩토링

2019-03-11 01:46 UTC, hyukjin-lee requested changes

2019-03-11 01:46 UTC, hyukjin-lee commented on src/main/java/codesquad/HtmlFormDataBuilder.java
> +}
테스트에서만 쓰이는 코드인데 프로덕션 코드에 위치하는게 말이 안되는 것 같습니다.

2019-03-11 01:46 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +
불필요한 공백

2019-03-11 01:46 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
OK 제대로 날라오나요? 그리고 loginForm을 잘 가져오는지에 대한 테스트는 단위테스트로 작성되어야합니다. 굳이 서버를 띄워서 확인해야되는 부분이 아니기 때문에 단위테스트로 가볍게 테스트 하는게 좋아요

2019-03-11 01:46 UTC, hyukjin-lee commented on src/test/java/codesquad/web/LoginAcceptanceTest.java
> +
어디는 띄고 어디는 안띄고 차이점을 모르겠습니다

2019-03-11 04:40 UTC, wijehyeon reviewed
👍

2019-03-11 04:40 UTC, wijehyeon commented on src/main/java/codesquad/web/UserController.java
> -    }
이 부분 왜 지우셨나요?

2019-03-11 04:40 UTC, wijehyeon commented on src/main/java/codesquad/web/UserController.java
> +            httpSession.setAttribute(HttpSessionUtils.USER_SESSION_KEY, userService.login(userId, password));
DTO에 대해서 공부해보면 좋을 것 같아요

2019-03-11 04:40 UTC, wijehyeon commented on src/main/resources/templates/user/login.html
> +            <form name="question" method="post" action="/users/login">
섬세하게 html링크까지 고쳐주셨네요
웹으로띄워서 테스트해보신건가요

2019-03-11 14:40 UTC, esp2ar0 commented on src/main/java/codesquad/web/UserController.java
> -    }
> 이 부분 왜 지우셨나요?

내용이 없어서 설정 파일에서 등록해준 듯 싶네요

2019-03-12 15:26 UTC, hyukjin-lee approved these changes

2019-03-12 15:26 UTC, merged